const products = [
{   id:1,
    name: "T1",
    price: 250,
    brand: "addidas",
    imgSrc: "./img/products/f1.jpg",
    instock: 10,
},
{   id:2,
    name: "T2",
    price: 300,
    brand: "puma",
    imgSrc: "./img/products/f2.jpg",
    instock: 10,
},
{   id:3,
    name: "T3",
    price: 230,
    brand: "gucci",
    imgSrc: "./img/products/f3.jpg",
    instock: 10,
},
{   id:3,
    name: "T4",
    price: 480,
    brand: "addidas",
    imgSrc: "./img/products/f4.jpg",
    instock: 10,
},
{   id:5,
    name: "T5",
    price: 400,
    brand: "lv",
    imgSrc: "./img/products/f5.jpg",
    instock: 10,
},
{   id:6,
    name: "T6",
    price: 1000,
    brand: "puma",
    imgSrc: "./img/products/f6.jpg",
    instock: 10,
},
{   id:7,
    name: "P1",
    price: 800,
    brand: "addidas",
    imgSrc: "./img/products/f7.jpg",
    instock: 10,
},
{   id:8,
    name: "TOP1",
    price: 800,
    brand: "addidas",
    imgSrc: "./img/products/f8.jpg",
    instock: 10,
},
{   id:9,
    name: "T7",
    price: 700,
    brand: "being human",
    imgSrc: "./img/products/n1.jpg",
    instock: 10,
},
{   id:10,
    name: "T8",
    price: 900,
    brand: "addidas",
    imgSrc: "./img/products/n2.jpg",
    instock: 10,
},
{   id:11,
    name: "T9",
    price: 300,
    brand: "killer",
    imgSrc: "./img/products/n3.jpg",
    instock: 10,
},
{   id:12,
    name: "T10",
    price: 800,
    brand: "prada",
    imgSrc: "./img/products/n4.jpg",
    instock: 10,
},
{   id:13,
    name: "T11",
    price: 30,
    brand: "addidas",
    imgSrc: "./img/products/n5.jpg",
    instock: 10,
},
{   id:14,
    name: "S1",
    price: 600,
    brand: "gucci",
    imgSrc: "./img/products/n6.jpg",
    instock: 10,
},
{   id:15,
    name: "T12",
    price: 3000,
    brand: "denim",
    imgSrc: "./img/products/n7.jpg",
    instock: 10,
},
{   id:16,
    name: "T13",
    price: 600,
    brand: "club",
    imgSrc: "./img/products/n8.jpg",
    instock: 10,
},
];
